export const strings = {
  title: 'Shoppe',
  intro: `Beautiful eCommerce UI Kit ${'\n'} for your online store`,
  onStart: "Let's get started",
  account: 'I already have an account',
  create: `Create ${'\n'}Account`,
  login: 'Login',
  loginTitle: 'Good to see you back!',
  greet: 'Hello,',
  logout: 'Logout',
  announcement: 'Announcement',
  lorem:
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas hendrerit luctus libero ac vulputate.',
  nextItem: 'Next Items',
  seeAll: 'See All',
  categories: 'Categories',
  justForYou: 'Just For You',
  id: 'Id',
  name: 'Title',
  price: 'Price',
  description: 'Description',
  returnPolicy: 'Return Policy',
  image: 'Upload Image',
  upload: 'Upload',
};
