export const images = {
  logo: require('../images/logo.png'),
  bubble1: require('../images/bubble 01.png'),
  bubble2: require('../images/bubble 02.png'),
  bubble3: require('../images/bubble 03.png'),
  bubble4: require('../images/bubble 04.png'),
  bubble5: require('../images/bubble 05.png'),
  bubble6: require('../images/bubble 06.png'),
  upload_photo: require('../images/Upload Photo.png'),
  cosmetic01: require('../images/cosmetic01.jpg'),
  cosmetic02: require('../images/cosmetic02.png'),
  cosmetic03: require('../images/cosmetic03.jpg'),
  cosmetic04: require('../images/cosmetic04.jpg'),
  beauty: require('../images/beauty.png'),
  fragrance: require('../images/fragrance.png'),
  furniture: require('../images/furniture.png'),
  groceries: require('../images/groceries.png'),
  all: require('../images/All.jpeg'),
};
